###Welcome to the first assignment of QBS 103!

#Instructions
* Write your code in the R code chunks provided.
* When you are finished with your assignment, upload this R Markdown file under Assignments tab on our class canvas page.
* MAKE SURE TO COMMENT YOUR CODE.
* You can work with your classmates, but remember to write their name in the comments.
* If you are inspired by code you found online make sure you cite the website, comment your code, and make it your own. No copy and pasting.

1) Below I have provided a list of random letters and numbers. Please conduct the following tasks on this list:
  a) What type of data is each of the "things" in the list? Write these types to a vector called "my_types". Pssssst here is a hint for how you might want to write this code: https://www.geeksforgeeks.org/adding-elements-in-a-vector-in-r-programming-append-method/#.
  b) Count how many of each data type appear in your vector.
  c) How many numbers in this list are greater than 5?
  d) Generate a factor of types from your "my_types" vector.
  e) Get the index (or indicies) of the number "1" in the lst list.

```{r}
lst <- list(4, 'j', 'Y', 5, 'f', 'K', 8, 'z', 'T', 'c', 0, 'B', 2, 'm', 'X', 9, 'd', 'V', 3, 'n', 'G', 6, 'h', 'J', 2, 'p', 'O', 1, 'q', 'R', 7, 's', 'D', 2, 'l', 'N', 0, 'w', 'E', 5, 'e', 'U', 4, 'i', 'P', 1, 'a', 'H', 8, 'y', 'S', 3, 'g', 'F', 9, 'b', 'M', 6, 'k', 'L', 7)
```

2) In the "data" folder of this repository there is a file called GSE165252_vst_PERFECT.txt. This is real RNA-seq data from a phase II clinical trial investigating the impact of combined impact PD-L1 inhibitor (atezolizumab) and neoadjuvant chemoradiotherapy on resectable esophageal adenocarcinoma patients. You can find a link to the data on GEO here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE165252. You can read about this study here: https://aacrjournals.org/clincancerres/article/27/12/3351/671431/Neoadjuvant-Chemoradiotherapy-Combined-with. Download the  GSE165252_vst_PERFECT.txt file to your local machine.
  a) Read in this file. Make sure you take into account that the first row contains Ensembl IDs (gene names)!
  b) How many samples are in this data set?
  c) How many genes are in this data set?
  d) Make a histogram of the expression values of a gene of your choosing from this data set.
  e) Subset this data to contain only their first three samples and first 2000 genes. Write this subset to a file called "eso_sub.csv".

  3) Write a function call "my_first_function". The function should take the following vector: my_vector <- c(1,2,3,4,5,6,7,8,9). Your function should sort the numbers in my_vector into two categories: less than or equal to 5 or greater than 5. Hint: You can take a look at for loops and if/else statements to complete this question!
